### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by TridentInsurgence** [DodgeTheDarins/Dodge-The-Darins#3]
broken
fix it
also add me trust
![Screenshot 2024-03-14 091605](https://github.com/user-attachments/assets/35be9093-9123-44d0-a6b8-5ba3d8c73a27)
![Screenshot 2024-06-11 143128](https://github.com/user-attachments/assets/60619762-2dcc-491d-ab2a-5eebaa55a4dd)

**Comment by hewiofhiowa** [comment]
Screw you I'm not fixing it lol

**Comment by DodgeTheDarins** [comment]
ok i'll fix it lol

**Comment by DodgeTheDarins** [comment]
also don't put ur face here you know this is public right?

**Comment by DodgeTheDarins** [comment]
fwalifjawoifjioawfjoiwfj godot stupid

**Comment by DodgeTheDarins** [comment]
wait why is it issue #3 if it's the first one

**Comment by DodgeTheDarins** [comment]
also i fixed it
